### ISSUE TITLE
Documentation Might Not Be Correct

### ISSUE THREAD

**Issue by nicorellius** [ivirabyan/django-mentions#1]
I love the idea of this app, and I hope it can work for me. But I ran into some issues when setting it up.

First, it seems importing `from mentions.providers import Provider` doesn't work, as providers.py doesn't exist. I found `Provider` class in the `registry.py` module.

Second, while this seems reasonable to assume, how do I load the filter? When I set it up as per your docs, and then I use like so `{{ post.text|urlize_mentions }}` I get errors saying that filter is invalid.

Any hints or tricks or tips?

**Comment by ivirabyan** [comment]
Thanks for reporting. I fixed documentation, you can import `Provider` directly from `mentions` module:

```
 from mentions import Provider
```

Previously the were no filter for native django template engine, only filter for Jinja template engine was present. I added support for django template system, so now you can do:

```
 {% load mentions %}
 {{ text|urlize_mentions }}
```

Let me know if it works for you, and I'll bump a new version into PyPi

**Comment by nicorellius** [comment]
Thanks for the reply. Couple things. First, upon installation, using a virtual environment with Python 3.3, I get an error on line 69 of `registry.py`:

`except ImportError, e:`

I changed this to:

`except ImportError as e:`

https://docs.python.org/3.0/whatsnew/2.6.html#pep-3110

This is just an observation, not a requirement...

And using `{% load mentions %}` is still giving errors:

`'mentions' is not a valid tag library`

I could totally be doing something wrong, but any ideas you have would be helpful. I will continue to investigate this. Just wanted to let you know what I found so far.

Thanks for your response!

**Comment by nicorellius** [comment]
I did some more work on this last night. I was able to get it to play nice but it's still not working (the actual templatetag is not filtering my text into links). I cloned the repo locally and will play around with it for my purposes. Perhaps we can collaborate to provide support for Python 3 and Django 1.7+? I'm using Django 1.6, 1.7 and 1.8 in my projects and Python 3.3/3.4 in several projects.

Here is what I did to make is not throw errors:

Since `get_user_model()` is deprecated since Django 1.5:
http://stackoverflow.com/questions/44109/extending-the-user-model-with-custom-fields-in-django

I used the User model instead.

Next, I changed the call to `unicode` to `str` in a few places for python 3 compatibility.

I had to add the `templatetag` directory, as well, since PyPi didn't include it when installing with `pip`.

So it's currently compatible with my stack but not working (showing hyperlinks). I will continue to work on this in my branch, if this is OK with you. Thanks again.

**Comment by ivirabyan** [comment]
get_user_model() was introduced in django 1.5, and is not deprecated: https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#django.contrib.auth.get_user_model

I didn't upload fixed code to PyPi yet, you should try code from github.

It might have issues with python 3, I didn't tested it there, but it should be simple to adapt the code.

**Comment by nicorellius** [comment]
You are right. My apologies... I was thinking of the `AUTH_PROFILE_MODULE` when I wrote that. I'm using profiles in my current project for mentions and I confused the two.

Thanks again for your help.
